spring:
  application:
    name: xoj-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: xoj-account-route
          uri: lb://xoj-account
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
