spring:
  application:
    name: xoj-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: xoj-account-route
          uri: lb://xoj-account
          predicates:
            - Path=/api/account/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: xoj-authority-route
          uri: lb://xoj-authority
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
